### PR TITLE
Adding adjoint runtime files

### PR DESCRIPTION
**Pull request by DaniJonesOcean**
I've added (most of the) runtime files that should be necessary for an adjoint run. However, we still need binary mask files to use as input. I haven't done those yet. 

Once we have those, we can do some test runs.

### CODE REVIEW

**Comment by ytakano3** [comment]
Thank you for adding this Dani. I will take a look at it soon. Yes we do need to prepare binary mask files, I haven't started working on it yet but will do soon.

**Comment by DaniJonesOcean** [comment]
Hi Yohei, 

I've added a few commits. They include:

- https://github.com/ytakano3/MITgcm_BGC_Model_Config/pull/2/commits/22796d298b0c51092d723566ba2bb31a1e0c2345: modified several of the input files based on our old oxygen adjoint setup
- https://github.com/ytakano3/MITgcm_BGC_Model_Config/pull/2/commits/6dc4866f1a2802a78c7f73c876d0a2df1755f991 : added some reference files from one of the oxygen adjoint setups
- https://github.com/ytakano3/MITgcm_BGC_Model_Config/pull/2/commits/fd3a732ec135768ead7b74a4355388c5026e8d3f : Got rid of some large files in the oxygen reference case that we don't need (I always forget how large STDOUT can get!)

I thought we could keep some of the oxygen adjoint reference files in this repository for now, in a separate folder, if that's okay. It's not structured enough to warrant its own repository, but I think we'd like to keep these files handy as we continue to develop this adjoint case. Let me know what you think!

**Comment by ytakano3** [comment]
Hi Dani (@DaniJonesOcean),

I am good including the O2 reference, now going through the adjoint input files and summarised my questions below.
I remember we went through this but need to recall (and write down on README). I have MITgcm binary IO Python routine so once I clarify these points, should be able to make mask files for this tutorial. Thanks!

O2_ad_reference

data.cal : What is the “calendarDumps” option?
data.ecco: The “gencost_avgperiod(1) = 'month’,” option can set the adjoint sensitivity frequency?
data.autodiff:  These two options are related to KPP and GMRedi, what is the reason behind turning these off (even though we are using KPP and GM Redi in this forward simulation?)
```
 “useKPPinAdMode = .FALSE.,”
 “useGMRediInAdMode = .FALSE.,”
```

input_ad

data.ctrl: I think I need to go through this part again.
 - For the weight file, I remember this contains ones (and zeros for bathymetry?) but also requires
time dimension (= period, so 14 days in this case).
 - Despite the fact we are not using calendar in this configuration, we need to set this (to define some
reference date) correct? How did you decide xx_gentim3d_startdate1 and 2?
 - Is there a reason why the period is 14 days (converted from seconds)?
 - What is mult_gentim3d?

```
xx_gentim3d_file(1)='xx_ptr01',
xx_gentim3d_weight(1) = 'wt_ones.data',
xx_gentim3d_startdate1(1) = 19920101,
xx_gentim3d_startdate2(1) = 60000,
xx_gentim3d_period(1) = 1209600.0,
mult_gentim3d(1) = 0.,
```

 - Why did you not set date, period for xx_genarr3d_file(1)?

data.optim: How do you set “optimcycle”? I see 0 in our example (but 12 for your ECCOv4r2 setup).

Masks to prepare

I need to clean up my head but we need to prepare,

- wt_ones.data: global weight data (four dimensional? x, y, z, and t?
e.g. xx_gentim3d_weight(1) = 'wt_ones.data',
-  mask3D: cost (objective) function, 3d mask for target cost function
e.g. gencost_mask(1) = 'mask3D',
- I also see maskCtrlC, maskCtrlS, maskCtrlW in O2 adjoint reference, I need to recall
we need these files correct? I couldn’t find a setting file referring these files and what do we
need to include in these files? Couldn’t track why we need to feed this in.

**Comment by ytakano3** [comment]
Following up, I just had a conversation with my colleague, "mask3D" will cover for both space (C) and time (T) so in this example I need mask3DC and mask3DT for the cost function files. Also noticed that we need "xx_ptr01" file(s) (depending on number of sensitivities we would like to explore). Any additional, clarification information are welcome.

**Comment by ytakano3** [comment]
Hi Dani (@DaniJonesOcean),

Following up, I figured out (recall) some of the information from your ECCOv4-r2 example. The weight data contains all ones (wt_ones.data), with an array structure: ECCOv4r2 (90, 1170, 50) and for the global 2.8 degrees, 15 levels (3deg15L) it should be (128, 64, 15) (correct me if the structure is wrong). MaskC is the Southern Ocean Mask (can we make this global? I see this is different from the cost (objective) function domain but why is this Southern Ocean?) and the array structure is (90, 1170, 50) (again for ECCOv4r2). MaskZ is a column (50), contains ones in your target depth range (upper 500m, filled with 1, the rest are 0). MaskT, I remember it is time but is this arbitrary to some extent? For ECCOv4-r2, the size is double the simulation length of time step (175295*2) but this depends on the length of adjoint simulations we would like to conduct and time step setting. Need to think of this for global 2.8 degrees, 15 levels model. Finally, the analysis (cost, objective function) mask is two-dimensional for ECCOv4r2 (90, 1170), but with regional mask (1 and 0, 1 some box in the Southern Ocean for example).

Sorry somewhat descriptive but hope we can clean up the array size for necessary mask input files. The remaining information I would like to clarify is the size of "xx_ptr01". Let me know if I mixed up something, would be great to clean up necessary files and "array structures". this is important.

**Comment by ytakano3** [comment]
Hi Dani (@DaniJonesOcean),

Following up, I figured out (recall) some of the information from your ECCOv4-r2 example. The weight data contains all ones (wt_ones.data), with an array structure: ECCOv4r2 (90, 1170, 50) and for the global 2.8 degrees, 15 levels (3deg15L) it should be (128, 64, 15) (correct me if the structure is wrong). MaskC is the Southern Ocean Mask (can we make this global? I see this is different from the cost (objective) function domain but why is this Southern Ocean?) and the array structure is (90, 1170, 50) (again for ECCOv4r2). MaskZ is a column (50), contains ones in your target depth range (upper 500m, filled with 1, the rest are 0). MaskT, I remember it is time but is this arbitrary to some extent? For ECCOv4-r2, the size is double the simulation length of time step (175295*2) but this depends on the length of adjoint simulations we would like to conduct and time step setting. Need to think of this for global 2.8 degrees, 15 levels model. Finally, the analysis (cost, objective function) mask is two-dimensional for ECCOv4r2 (90, 1170), but with regional mask (1 and 0, 1 some box in the Southern Ocean for example).

Sorry somewhat descriptive but hope we can clean up the array size for necessary mask input files. The remaining information I would like to clarify is the size of "xx_ptr01". Let me know if I mixed up something, would be great to clean up necessary files and "array structures". this is important.

**Comment by ytakano3** [comment]
@DaniJonesOcean I am writing updated notes (to be merged to the README file). Please follow me up if any information is missing (or spot any mistakes).

For the calendar (data.cal), I will leave it as it is, since we are not using the calendar in this configuration, it is just arbitrary from my understanding (calendarDumps causes chkPtFreq, pChkPtFreq, taveFreq, etc. to automatically conform their output to one calendar month if  we set chkptFreq  = 259200.0. for example, this is an information from the MITgcm-support). No needed here so turn it off.

Cost (objective) function (data.ecco) this is tied to time mask we will be generating. Here we set the gencost average period for a month and this is basically the period of averaging objective function. gencost mask can be set to 3d (by is3d option) so we don't need to prepare mask for horizontal and vertical separately (i.e. maskC and maskK, we can put 3d mask in mask C, hope this makes sense). Time is a bit tricky but e.g. if we are running forward and adjoint simulations for 10 years, we need to prepare maskT with 10 years * 12 months = 120 (time stamps) (and double that so 240). For an adjoint based on 1 year cost (objective) function, we can generate a weight (i.e. filling in the last 12 months with 1/12, 111-120 (time stamps, index). 

Using KPP and GMRedi in adjoint mode has been turned off (data.autodiff), because of the assumption behind (the structure of these parameterizations do NOT change with time) and also for stability reason.

Finally the control file (data.ctrl), wt_ones just contains ones with an array size of model grid, in this case 128, 64, 15 (i,j,k), and xx_XXX (e.g. xx_ptr01) will be automatically generated if we do not provide it (I remember filled with zeros but could you confirm what is in xx_XXX files? including the array size). gentim3d(2d)_period is set to 2 weeks (higher frequency than a month), this is the frequency settings for the adjoint sensitivity output, ... correct?

I think this is the latest information I have now, so need to prepare maskC, maskT (objective function), and wt_ones, for a test run. Again let me know if I missed something. Code to prepare masks are almost ready. Thank you!

**Comment by DaniJonesOcean** [comment]
> I am good including the O2 reference, now going through the adjoint input files and summarised my questions below. I remember we went through this but need to recall (and write down on README). I have MITgcm binary IO Python routine so once I clarify these points, should be able to make mask files for this tutorial. Thanks!
> 
> O2_ad_reference
> 
> data.cal : What is the “calendarDumps” option? 

I've not used this option before, but from the documentation this seems to be an option for having certain dump frequencies line up with calendar months/years. Here's where it's described in one of the header files:

https://github.com/MITgcm/MITgcm/blob/master/pkg/cal/cal.h#L102

>data.ecco: The “gencost_avgperiod(1) = 'month’,” option can set the adjoint sensitivity frequency? 

That parameter sets the basic averaging frequency of the objective function. See the section below for the different options for setting the frequency:

https://github.com/MITgcm/MITgcm/blob/master/pkg/cal/cal.h#L102

However, as we discussed, the actual period over which the average occurs (i.e. you could call it the the limits of the time integral) depends on both the `avgperiod` above and how you define the time mask. They need to be consistent with each other in a way that gets you what you want.

>data.autodiff: These two options are related to KPP and GMRedi, what is the reason behind turning these off (even though we are using KPP and GM Redi in this forward simulation?)
> 
> ```
>  “useKPPinAdMode = .FALSE.,”
>  “useGMRediInAdMode = .FALSE.,”
> ```
> 

As far as I am aware, it's common to turn off KPP and GM in adjoint mode to improve numerical stability. So, it's mostly a numerical issue.

> input_ad
> 
> data.ctrl: I think I need to go through this part again.
> 
> * For the weight file, I remember this contains ones (and zeros for bathymetry?) but also requires
>   time dimension (= period, so 14 days in this case).

You don't have to consider the bathymetry when making the weight files. But yes, I believe that you do have to include the time dimension. You need the number of indices in the time dimension equal to the number of averaging periods that you want to have in your simulation. This is another example of how you sort of have to plan out your adjoint simulation before even designing the masks. They are a bit more work-intensive than planning a forward run, in that way. 

> * Despite the fact we are not using calendar in this configuration, we need to set this (to define some
>   reference date) correct? How did you decide xx_gentim3d_startdate1 and 2?

I think we should use the `cal` package. Fortunately, we can set the actual start date to anything arbitrary that we like. But I believe the `cal` package is needed in order for the `ctrl` package to properly function, at least if we want to use the `gentim2d` controls (e.g. wind stress). 

> * Is there a reason why the period is 14 days (converted from seconds)?

It was just a decision. We were interested in annual mean objective functions, and I wanted a bit more granularity than monthly sensitivities. In hindsight, monthly probably would have been fine for my purposes, but it wasn't bad to have 14-day output. 

> * What is mult_gentim3d?

Those are control cost function multipliers, as described here:

https://mitgcm.readthedocs.io/en/latest/ocean_state_est/ocean_state_est.html#ecco-model-data-comparisons-using-gridded-data-sets

> 
> ```
> xx_gentim3d_file(1)='xx_ptr01',
> xx_gentim3d_weight(1) = 'wt_ones.data',
> xx_gentim3d_startdate1(1) = 19920101,
> xx_gentim3d_startdate2(1) = 60000,
> xx_gentim3d_period(1) = 1209600.0,
> mult_gentim3d(1) = 0.,
> ```
> 
> * Why did you not set date, period for xx_genarr3d_file(1)?

`xx_genarr3d` is not a time-varying control. It usually represents an initial condition or some mixing parameter coefficients. 

> 
> data.optim: How do you set “optimcycle”? I see 0 in our example (but 12 for your ECCOv4r2 setup).

That parameter represents a "step" in the optimization process. In machine learning, they call this "step" an "epoch". That is, one epoch is one cycle/iteration of improving the model initial conditions and surface forcing based on a single forward-and-backward sweep of the 4DVAR process. We can leave ours as 0, because we are not optimizing anything. The ECCOv4 example should be left at 12, because it has been through 12 iterations/epochs. 

> 
> Masks to prepare
> 
> I need to clean up my head but we need to prepare,
> 
> * wt_ones.data: global weight data (four dimensional? x, y, z, and t?
>   e.g. xx_gentim3d_weight(1) = 'wt_ones.data',

Yes, I believe that's correct for the `gemtim3d` controls.

> * mask3D: cost (objective) function, 3d mask for target cost function
>   e.g. gencost_mask(1) = 'mask3D',
> * I also see maskCtrlC, maskCtrlS, maskCtrlW in O2 adjoint reference, I need to recall
>   we need these files correct? I couldn’t find a setting file referring these files and what do we
>   need to include in these files? Couldn’t track why we need to feed this in.

I don't think we used these. Here's a bit more info about the masks:

https://mitgcm.readthedocs.io/en/latest/ocean_state_est/ocean_state_est.html#generic-integral-function

**Comment by DaniJonesOcean** [comment]
> Following up, I just had a conversation with my colleague, "mask3D" will cover for both space (C) and time (T) so in this example I need mask3DC and mask3DT for the cost function files. Also noticed that we need "xx_ptr01" file(s) (depending on number of sensitivities we would like to explore). Any additional, clarification information are welcome.

Yes, that sounds right to me!

The initial `xx_` files can be filled with zeros, with the expected dimensions (x,y,z,t) as a start.

**Comment by DaniJonesOcean** [comment]
> Hi Dani (@DaniJonesOcean),
> 
> Following up, I figured out (recall) some of the information from your ECCOv4-r2 example. The weight data contains all ones (wt_ones.data), with an array structure: ECCOv4r2 (90, 1170, 50) and for the global 2.8 degrees, 15 levels (3deg15L) it should be (128, 64, 15) (correct me if the structure is wrong). MaskC is the Southern Ocean Mask (can we make this global? I see this is different from the cost (objective) function domain but why is this Southern Ocean?) and the array structure is (90, 1170, 50) (again for ECCOv4r2). 

Yes, sorry for the confusion. As we discussed, you can ignore the "analysis mask" for now. And yes, those dimensions look okay to me, but I haven't checked lately. 

>MaskZ is a column (50), contains ones in your target depth range (upper 500m, filled with 1, the rest are 0). MaskT, I remember it is time but is this arbitrary to some extent? For ECCOv4-r2, the size is double the simulation length of time step (175295*2) but this depends on the length of adjoint simulations we would like to conduct and time step setting. 

Yes, I think that's right. From this section:

https://mitgcm.readthedocs.io/en/latest/ocean_state_est/ocean_state_est.html#generic-integral-function

We have "The ‘T’ vector length should match the # of records that the specification of gencost_avgperiod implies but there is no restriction on its values." I've always had to use 2x the number of records to avoid an "end of file" error, but it's possible that I'm using a longer vector than strictly necessary. 

>Need to think of this for global 2.8 degrees, 15 levels model. Finally, the analysis (cost, objective function) mask is two-dimensional for ECCOv4r2 (90, 1170), but with regional mask (1 and 0, 1 some box in the Southern Ocean for example).
> 

Yes, as we discussed, ignore the "analysis" mask. It's not the same as the objective function mask (i.e. cost function mask).

> Sorry somewhat descriptive but hope we can clean up the array size for necessary mask input files. The remaining information I would like to clarify is the size of "xx_ptr01". Let me know if I mixed up something, would be great to clean up necessary files and "array structures". this is important.

I think this is right. It's common to have to debug some mask issues when you're first getting started, though. You might run into some "end of file" errors. 

I'm really glad that you're cleaning up the approach to mask generation and making some useful python files. It's great!

**Comment by DaniJonesOcean** [comment]
> @DaniJonesOcean I am writing updated notes (to be merged to the README file). Please follow me up if any information is missing (or spot any mistakes).
> 
> For the calendar (data.cal), I will leave it as it is, since we are not using the calendar in this configuration, it is just arbitrary from my understanding (calendarDumps causes chkPtFreq, pChkPtFreq, taveFreq, etc. to automatically conform their output to one calendar month if we set chkptFreq = 259200.0. for example, this is an information from the MITgcm-support). No needed here so turn it off.

I'm not sure that `ctrl` will work without `cal`. I could be wrong, but I think if we want to use `gentim2d` and `gentim3d` variables as controls, we'll have to turn on `cal` eventually.

> 
> Cost (objective) function (data.ecco) this is tied to time mask we will be generating. Here we set the gencost average period for a month and this is basically the period of averaging objective function. gencost mask can be set to 3d (by is3d option) so we don't need to prepare mask for horizontal and vertical separately (i.e. maskC and maskK, we can put 3d mask in mask C, hope this makes sense). 

Yes, if we have set the flag to indicate that the mask is 3D, then we can just provide a `maskC` file, with dimensions of (lat, lon, depth). 

>Time is a bit tricky but e.g. if we are running forward and adjoint simulations for 10 years, we need to prepare maskT with 10 years * 12 months = 120 (time stamps) (and double that so 240). For an adjoint based on 1 year cost (objective) function, we can generate a weight (i.e. filling in the last 12 months with 1/12, 111-120 (time stamps, index).

I believe that's correct, yes. For consistency, in `data.ecco` we'll want to set the averaging period to `month`. 

> 
> Using KPP and GMRedi in adjoint mode has been turned off (data.autodiff), because of the assumption behind (the structure of these parameterizations do NOT change with time) and also for stability reason.

Yes, I believe that's right. 

> 
> Finally the control file (data.ctrl), wt_ones just contains ones with an array size of model grid, in this case 128, 64, 15 (i,j,k), and xx_XXX (e.g. xx_ptr01) will be automatically generated if we do not provide it (I remember filled with zeros but could you confirm what is in xx_XXX files? including the array size). gentim3d(2d)_period is set to 2 weeks (higher frequency than a month), this is the frequency settings for the adjoint sensitivity output, ... correct?

I think that's correct, yes. When constructing a state estimate, the `xx` files would contain the adjustments to the initial conditions and boundary conditions that are used to improve the model state. However, in our case, because we are not creating a state estimate, we can just have files with zeros (i.e. there are no adjustments). If I'm not mistaken, the `xx` files should have (x,y,z,t) as the dimensions, where the length of the time dimension is set by your `gentimXd_period` and the total length of the run.  

> 
> I think this is the latest information I have now, so need to prepare maskC, maskT (objective function), and wt_ones, for a test run. Again let me know if I missed something. Code to prepare masks are almost ready. Thank you!

Thanks, Yohei!

**Comment by ytakano3** [comment]
@DaniJonesOcean Hi Dani, thank you for all the follow ups, this is great! I started to try adjoint test simulations. The simulation is for 10 years duration (maskT contains 12 months * 10 years * 2 = 240 length of the file but the actual simulation is for 10 years).  Few things had to be fixed due to errors during execution, 

- Comment out an option in `ABIOTIC_PARMS`, `#selectK1K2const = 5`, not using the new carbonate chemistry.
- `** ERROR *** AUTODIFF_READPARMS: To use viscFacInFw/viscFacInAd, define AUTODIFF_ALLOW_VISCFACADJ`,  need to define a parameter to use `viscFacInAd`.
- `*** ERROR *** AUTODIFF_READPARMS: To use viscFacInFw/viscFacInAd, define ALLOW_3D_VISCA4 and/or ALLOW_3D_VISCA4`, need to define a parameter to use `viscFacInAd` (fyi perhaps there is a bug in error message, `ALLOW_3D_VISCAH` is the another parameter I think). For now I just turned on `ALLOW_3D_VISCA4` in `MOM_COMMON_OPTIONS.h`.

Basically I updated `AUTODIFF_OPTIONS.h` (this was quite different from the settings you provided and the current default settings), `MOM_COMMON_OPTIONS.h` and `data.dic` (including recompilation of the model). It complied (for adjoint) with additional settings but would like to warn that several INTERNAL ERROR showed up (but the model compiled). It seems like turning on `ALLOW_3D_VISCA4` is causing issues. I will share the errors for a reference.

```
INTERNAL ERROR: bldepth is not a module scope, cannot use object nr in bldepthmd
INTERNAL ERROR: ctrl_map_ini_gentim2d is not a module scope, cannot use object maxctrltim2d in ctrl_map_ini_gentim2dmd
INTERNAL ERROR: forward_step is not a module scope, cannot use object ptracers_num in forward_stepmd
INTERNAL ERROR: gmredi_slope_psi is not a module scope, cannot use object olx in gmredi_slope_psimd
INTERNAL ERROR: gmredi_slope_psi is not a module scope, cannot use object oly in gmredi_slope_psimd
INTERNAL ERROR: gmredi_slope_psi is not a module scope, cannot use object snx in gmredi_slope_psimd
INTERNAL ERROR: gmredi_slope_psi is not a module scope, cannot use object sny in gmredi_slope_psimd
INTERNAL ERROR: kppmix is not a module scope, cannot use object nrp1 in kppmixmd
INTERNAL ERROR: ri_iwmix is not a module scope, cannot use object imt in ri_iwmixmd
INTERNAL ERROR: ri_iwmix is not a module scope, cannot use object nrp1 in ri_iwmixmd
INTERNAL ERROR: thermodynamics is not a module scope, cannot use object ptracers_num in thermodynamicsmd
```
After going through these settings, the model actually do not recognize some namelist option, `The variable name 'XX_GENTIM3D_FILE' is unrecognized in namelist input.`.

I think we need to discuss again to make the execution work and will get back to you again later. Thank you.

**Comment by ytakano3** [comment]
@DaniJonesOcean Additional errors and fixing.
- `CTRL_OPTIONS.h`: changed to `#undef ALLOW_SMOOTH_CORREL3D`, `#undef ALLOW_SMOOTH_CORREL3D`, no longer allowed in `data.ctrl`, `*** ERROR *** S/R CTRL_READPARMS: Please use the smooth-pkg instead` but I have not turned on smooth-pkg, hope this does not matter.
- `data.pkg` : forgot to turn on diagnostics, now turned on.
-  `GMREDI_OPTIONS.h`: `*** ERROR *** Needs to define GM_READ_K3D_GM to use KAPGM_CONTROL`, `*** ERROR *** Needs to define GM_READ_K3D_REDI to use KAPREDI_CONTROL`, turned on both in `GMREDI_OPTIONS.h`.
- `MDSIO_BUFF_WH.h` : `*** ERROR *** ADWRITE: tapeFileCounter (=   451) > tapeMaxCounter (= nWh =   450)`, manually changed the `PARAMETER (nWh=618)` in the header file, to 618 (following the bling adjoint example), could adjust the number based on STDOUT information (debug level 3) (STDOUT gives tapeFileCounter =   605).
-  `tamc.h` : `** ERROR *** S/R GAD_ADVECTION: npass =  2 >  1 = maxcube, ==> check "tamc.h"`, PARAMETER( maxcube     = 2 ), set the maxcube to 2 now.

Now the adjoint model is running, still need to keep monitoring. WARNING still remains (`** WARNING ** AUTODIFF_READPARMS: For viscFacInFw/viscFacInAd to have any effect, specify at least one of viscAh[D/Z]file`) but I left this for now. I will update the files in pull request soon but please let me know if the changes I mentioned impact on results (or if you have suggestions).

I have second thoughts on `O2_ad_reference` files, I think we don't need to include this, the model has changed a lot since then and need to do new setups. Thanks!

**Comment by ytakano3** [comment]
I forgot one more thing, `gentim3d` was not recognized (only `gentim2d`) so had to comment out for now from `data.ctrl`. I searched the MITgcm repository a bit but could not find `gentim3d` related information (almost nothing). Is this something you added in your experiments?

**Comment by DaniJonesOcean** [comment]
> I forgot one more thing, `gentim3d` was not recognized (only `gentim2d`) so had to comment out for now from `data.ctrl`. I searched the MITgcm repository a bit but could not find `gentim3d` related information (almost nothing). Is this something you added in your experiments?

Oops, yes, this is an error - please change instances of `gentim3d` to `genarr3d`. Thanks!

**Comment by DaniJonesOcean** [comment]
> * `CTRL_OPTIONS.h`: changed to `#undef ALLOW_SMOOTH_CORREL3D`, `#undef ALLOW_SMOOTH_CORREL3D`, no longer allowed in `data.ctrl`, `*** ERROR *** S/R CTRL_READPARMS: Please use the smooth-pkg instead` but I have not turned on smooth-pkg, hope this does not matter.
> * `data.pkg` : forgot to turn on diagnostics, now turned on.
> * `GMREDI_OPTIONS.h`: `*** ERROR *** Needs to define GM_READ_K3D_GM to use KAPGM_CONTROL`, `*** ERROR *** Needs to define GM_READ_K3D_REDI to use KAPREDI_CONTROL`, turned on both in `GMREDI_OPTIONS.h`.
> * `MDSIO_BUFF_WH.h` : `*** ERROR *** ADWRITE: tapeFileCounter (=   451) > tapeMaxCounter (= nWh =   450)`, manually changed the `PARAMETER (nWh=618)` in the header file, to 618 (following the bling adjoint example), could adjust the number based on STDOUT information (debug level 3) (STDOUT gives tapeFileCounter =   605).
> * `tamc.h` : `** ERROR *** S/R GAD_ADVECTION: npass =  2 >  1 = maxcube, ==> check "tamc.h"`, PARAMETER( maxcube     = 2 ), set the maxcube to 2 now.
> 

Fantastic, thanks for doing all of that!

> Now the adjoint model is running, still need to keep monitoring. WARNING still remains (`** WARNING ** AUTODIFF_READPARMS: For viscFacInFw/viscFacInAd to have any effect, specify at least one of viscAh[D/Z]file`) but I left this for now. I will update the files in pull request soon but please let me know if the changes I mentioned impact on results (or if you have suggestions).

This appears to be a warning message that was introduced about three years ago:

https://github.com/MITgcm/MITgcm/commit/4240547d2d8f9b0cf5562f8dbad8a34b479a9189

It seems like we need to include a file if we want the viscosity to be different between the forward and backwards run. I'm not sure how the file should be structured - Matt Mazloff would be a good person to ask about this (or Gael). 

> 
> I have second thoughts on `O2_ad_reference` files, I think we don't need to include this, the model has changed a lot since then and need to do new setups. Thanks!

That's okay! We don't have to include it. You can delete it, if you like.

**Comment by ytakano3** [comment]
@DaniJonesOcean Thanks Dani! One last thing, would it be fine to ignore the `INTERNAL ERROR:` messages we have now during compilation?

**Comment by ytakano3** [comment]
@DaniJonesOcean I will merge the pull request for now, I think we had good discussion and changes here. Still need update and cleaning of files but will work on that after merging to the main branch.

**Comment by DaniJonesOcean** [comment]
> @DaniJonesOcean I will merge the pull request for now, I think we had good discussion and changes here. Still need update and cleaning of files but will work on that after merging to the main branch.

Sorry for the delay on this one. I haven't run into those particular "module scope" messages before. It's a bit concerning because some of those parameters are related to the domain tiling (e.g. `sNx`). Are they still popping up?

**Pull request merged**
