### PR TITLE
Introducing the code_ad folder

### PR DESCRIPTION
**Pull request by DaniJonesOcean**
This pull request introduces the `code_ad` folder for adjoint compilation. It uses a basic adjoint configuration from this working configuration of a shelf seas model:

https://github.com/DaniJonesOcean/MCS

Unlike MCS, our BGC configuration uses the `dic`, `gchem`, and `gmredi` packages. So we have introduced header files and options for those. 

Here are a few key features/notes:

- DIC_OPTIONS.h: 
-- (Line 25) #undef CARBONCHEM_SOLVESAPHE
-- (Line 31) #define CARBONCHEM_TOTALPHSCALE
- GMREDI_OPTIONS.h:
-- (Line 28) #define GM_EXCLUDE_SUBMESO
-- Debugged issues related to the variables `passkey` and `nobcs`
- Header files for AUTODIFF, CPP, CTRL, ECCO and tamc:
-- Used configurations from a MCS.

This adjoint case has been tested and does compile successfully. It has *not* been tested at runtime. It's a start!

### CODE REVIEW

**Comment by ytakano3** [comment]
Thank you for the pull request Dani (@DaniJonesOcean). I am glad the compilation worked out. One thing I am curious is about the differences in header files you copied from MCS configurations. MITgcm checkpoint differs so when I compared with the header files in the checkpoint I am using (68r) to configure this model, I see substantial changes but do these changes matter (perhaps not since you managed to compile the model)? What I will do is try compiling the adjoint with your files and also with the updated header files. Also could you follow up a bit more in details on debugged issues related to the variables `passkey` and `nobcs`? These might be solved by changing GMREDI_OPTIONS.h but just to be clear.

**Comment by ytakano3** [comment]
@DaniJonesOcean I manage to compile the adjoint code. No errors and executable file is generated. I checked all the codes carefully and related to the first comment, I would like to add notes on what we need to keep in mind for adjoint modeling (necessary header files, debugging tips from what we learned in this case etc.). Couple of notes on clarification,

- **CTRL_SIZE.h**: How do you set this? What is set by this option?
- **DIC_VARS.h**: Changing COMMON BLOCK does not impact the result? Perhaps not in this case since we turned the carbonate solver option off.
- **PTRACERS_SIZE.h**: Adding lines below.
 #ifdef ALLOW_AUTODIFF_TAMC
       INTEGER    maxpass
       PARAMETER( maxpass     = PTRACERS_num + 2 )
 #endif
- **SIZE.h**: Comment out nobsc lines.
- **tamc.h**: What is the main point to keep in mind (changing from default)?

Once I made a note on changes, will merge to the main branch.

**Comment by DaniJonesOcean** [comment]
I made changes related to `passkey` baed on this issue:

https://github.com/MITgcm/MITgcm/pull/669

And `nobcs` was related to this issue:

https://github.com/MITgcm/MITgcm/pull/749

**Comment by DaniJonesOcean** [comment]
Hi Yohei,

Below is some text that I wrote about the `nchklev` parameters in `tamc.h`. We could add it to the README.md file for convenience.

### Checkpointing

In an adjoint run, there is a balance between storage (i.e. saving the model state to disk) and recomputation (i.e. integrating the model forward from a stored state). Changing the `nchklev` parameters in the `tamc.h` file is how you control the relative balance between storage and recomputation. 

A suggested strategy that has been used on a variety of HPC platforms is as follows. 

1. Set `nchklev_1` as large as possible, up to the size allowed by memory on your machine. (Use the `size` command to estimate the memory per process. This should be just a little bit less than the maximum allowed on the machine).
2. Next, set `nchklev_2` and `nchklev_3` to be large enough to accomodate the entire run. A common strategy is to set `nchklev_2 = nchklev_3 = sqrt(numsteps/nchklev_1) + 1`. 
3. If the `nchklev_2` files get too big, then you may have to add a fourth level (i.e. `nchklev_4`), but this is unlikely. 

This strategy allows you to keep as much in memory as possible, minimising the I/O requirements for the disk. This is useful, as I/O is often the bottleneck for MITgcm runs on HPC. 

Another way to adjust performance is to adjust how tapelevel I/O is handled. Although it is machine dependent, the following strategy by Gael Forget has worked well in the past:
```
C o tape settings
#define ALLOW_AUTODIFF_WHTAPEIO
#define AUTODIFF_USE_OLDSTORE_2D
#define AUTODIFF_USE_OLDSTORE_3D
#define EXCLUDE_WHIO_GLOBUFF_2D
#define ALLOW_INIT_WHTAPEIO
```

## Defining the masks 
The generic cost function approach allows one to define the objective function as an integral over space and time. We include some example scripts for creating masks in this repository. For more information, see this part of the MITgcm documentation:

https://mitgcm.readthedocs.io/en/latest/ocean_state_est/ocean_state_est.html#generic-cost-function

**Comment by DaniJonesOcean** [comment]
@ytakano3, I've added a couple new commits for changing the README.md

**Comment by ytakano3** [comment]
@DaniJonesOcean Thank you for the updates Dani. I just checked the README and notes, finished updating. Mainly adding more notes, nothing changed fundamentally. I will merge this PR to the main branch. We can work on an example (objective function, mask etc.) in the next PR.

**Pull request merged**
